### ISSUE TITLE
create a --no-geoip switch for VPNs whose status includes the country

### ISSUE THREAD

**Issue by shervinsahba** [shervinsahba/polybar-vpn-controller#8]
The idea is that certain VPNs will report the country in their status call, negating the need for geoiplookup. See the TODO comment left by @sudo-julia in `vpn_module.sh` under [this branch](https://github.com/shervinsahba/polybar-vpn-controller/tree/8-create-a---no-geoip-switch-for-vpns-wh), which suggests using `country_codes.py` script to get the current country.

**Comment by jamc-code** [comment]
Hey! I think this should be really easy to integrate. The biggest thing is going to be finding what providers include the country in the status, because I only have access to Mullvad. One method that might work is digging through the [polybar-scripts](https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts) repository and reading the code that individual VPN modules use to display their status.

**Comment by shervinsahba** [comment]
Started to do this with the recent changes and `vpn_module status <method>` with <method> being `mullvad`, `other-vpn`, `geo-ip`, and `ip`. The first two methods begin to address this. Will mark closed for now until specific methods are added for other VPNs.
